name: merge

on:
  push:
    branches:
      - master
      - alpha
      - beta

env:
  BASE_DIR: "."
  NODE_VERSION: "12.x"
  JAVA_VERSION: "11"
  #  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  #NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: dependency-test
      run: |
        mvn dependency:go-offline
      working-directory: ${{ env.BASE_DIR }}
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  
    - name: unit-test
      run: |
        mvn clean test -U
      working-directory: ${{ env.BASE_DIR }}
    #- name: Service Tests
    #  run: |
    #   ../deploy/scripts/integration_test.sh
    #  working-directory: ${{ env.BASE_DIR }}

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: increase patch version
        if: "contains(github.event.head_commit.message, 'fix')"
        run: |
          mvn build-helper:parse-version versions:set \
          -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} \
          versions:commit
        working-directory: ${{ env.BASE_DIR }}

      - name: increase minor version
        if: "contains(github.event.head_commit.message, 'feat')"
        run: |
          mvn build-helper:parse-version versions:set \
          -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0 \
          versions:commit
        working-directory: ${{ env.BASE_DIR }}

      - name: increase major version
        if: "contains(github.event.head_commit.message, 'perf')"
        run: |
          mvn build-helper:parse-version versions:set \
          -DnewVersion=\${parsedVersion.nextMajorVersion}.0.0 \
          versions:commit
        working-directory: ${{ env.BASE_DIR }}
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
